# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

production:
 url: postgres://qnipshnfeuzbxo:sxPQYuThxULSHyR_zjW4LfrF10@ec2-54-83-202-64.compute-1.amazonaws.com:5432/d8m87fv67cn1hi
 #adapter: postgresql
 #database: de2sf3ksv430bm
 #username: pqqtpvmwrnaivs
 #password: Jds52pPL4gm2IKcFJMpbyXERyB
 #host: ec2-54-83-202-64.compute-1.amazonaws.com
 #port: 5432 




